### ISSUE TITLE
I couldn't get uart1 running

### ISSUE THREAD

**Issue by sakhnik** [IndoorCorgi/picoboot3#1]
I want to use uart1 (pins 4, 5) for my project because uart0 is used for other periphery. But I can't get it initialized properly.

- I'm sure the connection is right because my app can print debug logs via it when booted
- I tried tweaking `picoboot3_uart_init` up to using `stdio_uart_init_full` to just output a hello string but to no avail

I ran out of ideas at the moment. What could be wrong?

**Comment by IndoorCorgi** [comment]
Pin 4 and 5 are used for I2C by default. To use it as UART, you need to change I2C pins to avoid conflicts. 
Change picoboot3.h like below:
~~~
// UART setting to communicate with the host
#define PICOBOOT3_UART_INST uart1
#define PICOBOOT3_UART_TX_PIN 4
#define PICOBOOT3_UART_RX_PIN 5
...

// I2C setting to communicate with the host
#define PICOBOOT3_I2C_INST i2c_default
#define PICOBOOT3_I2C_SDA_PIN 8
#define PICOBOOT3_I2C_SCL_PIN 9
~~~

**Comment by sakhnik** [comment]
Yes, that works! Thanks for the support!
